### ISSUE TITLE
script

### ISSUE THREAD

**Issue by bpwl0121** [hoangthangta/ThangKAN#2]
Hi,

thanks for your work.
from the README, seems like you use same 'mlp' network for both TransformerMLP and TransformerClassifier?
`python run_train.py --mode "train" --network "mlp" --em_model_name "bert-base-cased" --ds_name "wnli" --epochs 10 --batch_size 4 --max_len 512 --n_size 1 --m_size 768 --n_hidden 64 --n_class 2 --embed_type "pool"`

**Comment by hoangthangta** [comment]
Hi, that is my mistake. TransformerMLP uses **--network "mlp"** and TransformerClassifier with **--network "classifier"**.

TransformerMLP

```python run_train.py --mode "train" --network "mlp" --em_model_name "bert-base-cased" --ds_name "wnli" --epochs 10 --batch_size 4 --max_len 512 --n_size 1 --m_size 768 --n_hidden 64 --n_class 2 --embed_type "pool"```

TransformerClassifier

```python run_train.py --mode "train" --network "classifier" --em_model_name "bert-base-cased" --ds_name "wnli" --epochs 10 --batch_size 4 --max_len 512 --n_size 1 --m_size 768 --n_hidden 64 --n_class 2 --embed_type "pool"```

**Comment by bpwl0121** [comment]
you use the correct scripts with the results you show in the README, right?

**Comment by hoangthangta** [comment]
Yes, it is correct.
